import type {
  AdminLog,
  AdminReport,
  Banner,
  CommunityBoard,
  CommunityComment,
  CommunityGroup,
  CommunityMembership,
  DailyCategory,
  DailyFeed,
  FeedComment,
  FeedImage,
  FeedLike,
  HelpCategory,
  HelpReport,
  Job,
  Notice,
  Place,
  PlaceReport,
  Post,
  SavedItem,
  SupportInstitution,
  User,
  UserProfileRecord,
  Workplace,
} from './types'
import sampleUsersData from './data/sampleUsers.json'
import communityGroupsData from './data/communityGroups.json'
import communityBoardsData from './data/communityBoards.json'
import communityMembershipsData from './data/communityMemberships.json'
import helpCategoriesData from './data/helpCategories.json'
import supportInstitutionsData from './data/supportInstitutions.json'

const regions = ['경기 안산', '경기 시흥', '충북 청주', '충북 음성', '경남 김해', '경남 창원', '충남 천안', '전남 광주', '대구 달서', '경북 경산', '부산 사상', '전북 익산', '제주 제주시']
const nationalities = ['Vietnam', 'China', 'Uzbekistan', 'Vietnam', 'China', 'Uzbekistan']
const authors = ['Mina', 'Ali', 'Sara', 'Tuan', 'Rafi', 'Nika', 'Linh', 'Somchai', 'Anil', 'Grace']
const categories: DailyCategory[] = ['회사생활', '한국생활', '음식', '쉬는날', '숙소생활', '질문', '자랑/축하', '조심하세요']
const placeCategories = ['상담', '병원', '생활', '한국어교육', '송금', '마트', '쉼터', '행정']
const helpTypes = ['임금 문제', '계약 문제', '주거 문제', '폭언/폭행', '사기', '여권/신분증 보관', '의료/사고', '통역 필요', '기타']
const sampleUsers = sampleUsersData
export const communityGroups = communityGroupsData as CommunityGroup[]
export const communityBoards = communityBoardsData as CommunityBoard[]
export const communityMemberships = communityMembershipsData as CommunityMembership[]
export const helpCategories = helpCategoriesData as HelpCategory[]
export const supportInstitutions = supportInstitutionsData as SupportInstitution[]

function sampleUserFields(index: number) {
  const user = sampleUsers[index % sampleUsers.length]
  const verified = user.verificationStatus === 'verified'
  return {
    authorId: Number(user.id),
    displayName: user.displayName,
    username: user.username,
    userId: `user-${user.id}`,
    avatarUrl: user.avatarUrl || undefined,
    countryCode: user.countryCode,
    countryName: user.countryName,
    flagIconUrl: user.flagIconUrl || undefined,
    flagEmoji: user.flagEmoji,
    isCountryVerified: user.isCountryVerified,
    isVerified: verified,
    verificationStatus: user.verificationStatus as 'verified' | 'unverified' | 'pending',
    preferredLanguage: user.preferredLanguage as User['preferredLanguage'],
    gradientColors: user.gradientColors,
  }
}

export const users: User[] = Array.from({ length: 12 }, (_, index) => ({
  id: index + 1,
  name: authors[index % authors.length],
  ...sampleUserFields(index),
  nationality: nationalities[index % nationalities.length],
  region: regions[index % regions.length],
  visa: ['E-9', 'H-2', 'F-6', 'F-2'][index % 4],
  status: index === 4 ? 'blocked' : index % 5 === 1 ? 'warned' : 'active',
  warnings: index === 4 ? 3 : index % 5 === 1 ? 1 : 0,
}))

export const userProfiles: UserProfileRecord[] = users.map((user, index) => ({
  userId: user.id,
  language: index % 3 === 0 ? 'vi' : index % 3 === 1 ? 'en' : 'ko',
  nationality: user.nationality,
  region: user.region,
  visa: user.visa,
  interests: [['일자리', '의료'], ['생활지도', '한국어'], ['노동상담', '커뮤니티']][index % 3],
}))

export const workplaces: Workplace[] = Array.from({ length: 20 }, (_, index) => ({
  id: index + 1,
  name: `${regions[index % regions.length].split(' ').at(-1)} 글로벌워크 ${index + 1}`,
  region: regions[index % regions.length],
  reviewScore: 3.5 + (index % 6) * 0.2,
  riskTags: index % 7 === 0 ? ['급여 확인 필요'] : index % 9 === 0 ? ['숙소비 공제 확인'] : [],
}))

const jobVisaProfiles = [
  {
    category: 'manufacturing',
    industryCode: 'manufacturing',
    employmentType: 'full-time',
    allowedVisaTypes: ['E-9', 'H-2', 'F-2', 'F-5', 'F-6'],
    restrictedVisaTypes: ['D-2', 'D-4'],
    cautionVisaTypes: ['F-4', 'E-7', 'E-7-4'],
    visaNote: '제조업 공고로 분류되어 E-9 허용 업종에 해당할 수 있습니다. F-4는 단순노무 해당 여부 확인이 필요합니다.',
    isVisaFriendly: true,
    requiresVisaCheck: true,
  },
  {
    category: 'manufacturing',
    industryCode: 'cold-storage',
    employmentType: 'full-time',
    allowedVisaTypes: ['E-9', 'H-2', 'F-2', 'F-5', 'F-6'],
    restrictedVisaTypes: ['D-2', 'D-4'],
    cautionVisaTypes: ['F-4'],
    visaNote: '물류·저온창고 업무는 세부 직무와 체류자격 조건 확인이 필요합니다.',
    isVisaFriendly: true,
    requiresVisaCheck: true,
  },
  {
    category: 'hotel-support',
    industryCode: 'hotel-support',
    employmentType: 'part-time',
    allowedVisaTypes: ['H-2', 'F-2', 'F-5', 'F-6'],
    restrictedVisaTypes: ['E-9'],
    cautionVisaTypes: ['D-2', 'D-4', 'F-4'],
    visaNote: '호텔 지원 업무는 직무 범위에 따라 비자 적합성 확인이 필요합니다.',
    isVisaFriendly: true,
    requiresVisaCheck: true,
  },
  {
    category: 'logistics',
    industryCode: 'simple-labor',
    employmentType: 'full-time',
    allowedVisaTypes: ['H-2', 'F-2', 'F-5', 'F-6'],
    restrictedVisaTypes: ['D-2', 'D-4'],
    cautionVisaTypes: ['E-9', 'F-4', 'E-7', 'E-7-4'],
    visaNote: '단순 분류 업무는 체류자격별 제한 여부 확인이 필요합니다.',
    isVisaFriendly: false,
    requiresVisaCheck: true,
  },
  {
    category: 'agriculture',
    industryCode: 'agriculture',
    employmentType: 'full-time',
    allowedVisaTypes: ['E-9', 'H-2', 'F-2', 'F-5', 'F-6'],
    restrictedVisaTypes: ['D-2', 'D-4'],
    cautionVisaTypes: ['F-4'],
    visaNote: '농업 공고로 분류되어 E-9 허용 업종에 해당할 수 있습니다.',
    isVisaFriendly: true,
    requiresVisaCheck: true,
  },
  {
    category: 'food-service',
    industryCode: 'food-service',
    employmentType: 'part-time',
    allowedVisaTypes: ['H-2', 'F-2', 'F-5', 'F-6'],
    restrictedVisaTypes: ['E-9'],
    cautionVisaTypes: ['D-2', 'D-4', 'F-4'],
    visaNote: '음식점·서비스 공고는 E-9 비자에 적합하지 않을 수 있습니다. 유학·연수 비자는 자격외활동 허가 확인이 필요합니다.',
    isVisaFriendly: false,
    requiresVisaCheck: true,
  },
  {
    category: 'technical',
    industryCode: 'manufacturing-skilled',
    employmentType: 'full-time',
    allowedVisaTypes: ['E-7', 'E-7-4', 'F-2', 'F-5', 'F-6'],
    restrictedVisaTypes: ['D-2', 'D-4'],
    cautionVisaTypes: ['E-9', 'F-4'],
    visaNote: '숙련기능 또는 기술 직무로 분류될 수 있어 직종코드와 자격요건 확인이 필요합니다.',
    isVisaFriendly: true,
    requiresVisaCheck: true,
  },
]

const jobRegionCodes: Record<string, { regionCode: string; cityCode?: string; districtCode?: string }> = {
  '경기 안산': { regionCode: 'GG', cityCode: 'GG-ANSAN' },
  '경기 시흥': { regionCode: 'GG', cityCode: 'GG-SIHEUNG' },
  '충북 청주': { regionCode: 'CB', cityCode: 'CB-CHEONGJU', districtCode: 'CB-CHEONGJU-CHEONGWON' },
  '충북 음성': { regionCode: 'CB', cityCode: 'CB-EUMSEONG' },
  '경남 김해': { regionCode: 'GN', cityCode: 'GN-GIMHAE' },
  '경남 창원': { regionCode: 'GN', cityCode: 'GN-CHANGWON' },
  '충남 천안': { regionCode: 'CN', cityCode: 'CN-CHEONAN' },
  '전남 광주': { regionCode: 'GJ' },
}

export const jobs: Job[] = Array.from({ length: 20 }, (_, index) => {
  const pending = index % 6 === 1
  const visaProfile = jobVisaProfiles[index % jobVisaProfiles.length]
  const region = regions[index % regions.length]
  const regionCodes = jobRegionCodes[region] || {}
  return {
    id: index + 1,
    title: ['자동차 부품 포장 정보', '식품 제조 라인 보조', '호텔 객실 정비', '물류센터 분류 보조', '농산물 선별 작업'][index % 5],
    company: workplaces[index].name,
    region,
    ...regionCodes,
    district: region.split(' ').at(-1),
    category: visaProfile.category,
    industryCode: visaProfile.industryCode,
    employmentType: visaProfile.employmentType,
    salary: index % 3 === 0 ? `시급 ${(10030 + (index % 8) * 320).toLocaleString()}원` : `월 ${230 + (index % 6) * 10}만원 내외`,
    visa: index % 2 === 0 ? ['E-9', 'H-2'] : ['H-2', 'F-6'],
    wage: 10030 + (index % 8) * 320,
    payLabel: index % 3 === 0 ? `시급 ${(10030 + (index % 8) * 320).toLocaleString()}원` : `월 ${230 + (index % 6) * 10}만원 내외`,
    tags: [['주간', '기숙사'], ['잔업가능', '식사제공'], ['파트타임', '도심'], ['통근버스', '초보가능']][index % 4],
    shift: ['08:30 - 17:30', '09:00 - 18:00', '10:00 - 16:00', '20:00 - 05:00'][index % 4],
    description: '근무 조건을 확인할 수 있는 정보 제공용 공고입니다. 직접 채용 알선이 아니며 계약 전 근로조건 확인이 필요합니다.',
    allowedVisaTypes: visaProfile.allowedVisaTypes,
    restrictedVisaTypes: visaProfile.restrictedVisaTypes,
    cautionVisaTypes: visaProfile.cautionVisaTypes,
    visaNote: visaProfile.visaNote,
    isVisaFriendly: visaProfile.isVisaFriendly,
    requiresVisaCheck: visaProfile.requiresVisaCheck,
    source: pending ? 'user' : 'operator',
    approvalStatus: pending ? 'pending' : 'approved',
    saved: index % 8 === 0,
    hidden: index % 13 === 0,
    deleted: false,
    complianceNote: pending ? '사용자 등록. 불법 알선 표현 검수 필요' : '직접 알선 표현 없음',
  }
})

const lifeMapCategories = ['병원', '약국', '상담기관', '송금/은행', '통신/유심', '음식점/마트', '행정기관', '안전/산재', '종교/커뮤니티']
const lifeMapServices = [
  ['야간진료', '외국인 접수 안내', '진료비 안내'],
  ['상비약', '처방전 조제', '복약 상담'],
  ['노동상담', '통역 연결', '기관 안내'],
  ['해외송금', '계좌개설 안내', 'ATM'],
  ['유심 개통', '요금제 상담', '휴대폰 수리'],
  ['할랄/현지 식품', '생활용품', '저렴한 식사'],
  ['출입국 업무', '행정 서류', '체류 상담'],
  ['산재 상담', '긴급 안내', '안전 교육'],
  ['모임', '예배/기도', '생활정보 교류'],
]

const lifeMapRegionCenters: Record<string, { lat: number; lng: number }> = {
  '경기 안산': { lat: 37.3219, lng: 126.8309 },
  '경기 시흥': { lat: 37.3802, lng: 126.8029 },
  '충북 청주': { lat: 36.6357, lng: 127.4913 },
  '충북 음성': { lat: 36.9404, lng: 127.6906 },
  '경남 김해': { lat: 35.2285, lng: 128.8893 },
  '경남 창원': { lat: 35.2279, lng: 128.6819 },
  '충남 천안': { lat: 36.8151, lng: 127.1139 },
  '전남 광주': { lat: 35.1595, lng: 126.8526 },
  '대구 달서': { lat: 35.8562, lng: 128.4919 },
  '경북 경산': { lat: 35.8251, lng: 128.7415 },
  '부산 사상': { lat: 35.1527, lng: 128.9914 },
  '전북 익산': { lat: 35.9483, lng: 126.9576 },
  '제주 제주시': { lat: 33.4996, lng: 126.5312 },
}

function lifeMapCoordinate(region: string, index: number) {
  const center = lifeMapRegionCenters[region] || { lat: 36.713, lng: 127.429 }
  const latOffset = ((((index * 7) % 11) - 5) * 0.006)
  const lngOffset = ((((index * 5) % 13) - 6) * 0.007)
  return {
    lat: Number((center.lat + latOffset).toFixed(6)),
    lng: Number((center.lng + lngOffset).toFixed(6)),
  }
}

function placeReviewTemplates(place: Pick<Place, 'category' | 'region' | 'name'>) {
  if (place.category.includes('병원')) {
    return [
      '접수할 때 외국인등록증과 건강보험 여부를 먼저 물어봐서 준비하기 쉬웠어요.',
      '증상을 번역 앱으로 보여주니 안내가 빨랐고, 진료비 설명도 다시 확인해줬습니다.',
      `${place.region}에서 야간이나 주말 방문 전 전화 확인하고 가면 헛걸음이 적어요.`,
    ]
  }
  if (place.category.includes('약국')) {
    return [
      '약 이름을 몰라도 증상 사진을 보여주니 복용 방법을 천천히 설명해줬어요.',
      '처방전이 필요한 약과 바로 살 수 있는 약을 구분해서 알려줘서 도움이 됐습니다.',
      '한국어가 어려우면 먹는 시간과 횟수를 메모로 받아두면 안전해요.',
    ]
  }
  if (place.category.includes('상담') || place.category.includes('안전') || place.category.includes('산재')) {
    return [
      '임금이나 계약 문제를 말할 때 근로계약서 사진을 가져가니 상담이 훨씬 빨랐어요.',
      '처음에는 어디에 물어봐야 할지 몰랐는데 담당 기관을 연결해줘서 안심됐습니다.',
      '방문 전에 상담 가능 언어와 예약 시간을 전화로 확인하는 게 좋습니다.',
    ]
  }
  if (place.category.includes('송금')) {
    return [
      '송금 수수료와 환율을 비교해서 알려줘서 급여일에 이용하기 편했어요.',
      '여권이나 외국인등록증 필요 여부를 미리 확인하고 가면 시간이 줄어듭니다.',
      'ATM 위치와 영업시간을 같이 확인해두면 퇴근 후에도 계획하기 좋아요.',
    ]
  }
  if (place.category.includes('행정')) {
    return [
      '체류지 변경이나 민원 서류를 물어볼 때 필요한 준비물을 먼저 알려줬어요.',
      '대기 시간이 있을 수 있어서 오전에 가거나 번호표 시간을 확인하는 게 좋습니다.',
      '한국어가 어려우면 서류 이름을 캡처해서 보여주는 방식이 도움이 됐어요.',
    ]
  }
  if (place.category.includes('통신')) {
    return [
      '유심 요금제 조건과 약정 여부를 비교해서 설명해줘서 선택하기 쉬웠어요.',
      '여권 개통 가능 여부와 외국인등록증 필요 여부를 미리 확인하면 좋습니다.',
      '데이터가 많이 필요한 사람은 월 요금과 충전 방식을 꼭 같이 물어보세요.',
    ]
  }
  if (place.category.includes('음식') || place.category.includes('마트')) {
    return [
      '고향 식재료를 찾기 쉬워서 쉬는 날 장 보러 가기 좋았어요.',
      '가격표가 비교적 잘 보이고 직원에게 물어보면 추천 상품도 알려줬습니다.',
      '퇴근 시간에는 사람이 많아서 주말 오전에 가면 더 편합니다.',
    ]
  }
  if (place.category.includes('밀집')) {
    return [
      '처음 이 지역에 왔을 때 병원, 마트, 송금 장소를 한 번에 확인하기 좋았어요.',
      '같은 국적 사람을 만날 수 있는 가게와 커뮤니티 정보가 많아서 적응에 도움이 됩니다.',
      '일자리와 숙소를 알아볼 때 주변 생활권을 먼저 확인하면 이동 동선이 줄어듭니다.',
    ]
  }
  if (place.category.includes('종교') || place.category.includes('커뮤니티')) {
    return [
      '쉬는 날 모임 정보를 알 수 있어서 혼자 지내는 느낌이 덜했어요.',
      '한국 생활 질문을 편하게 물어볼 수 있고 필요한 기관 정보도 같이 공유됩니다.',
      '처음 참여할 때는 운영 시간과 가입 조건을 먼저 확인하는 게 좋아요.',
    ]
  }
  return [
    `${place.name} 정보를 보고 방문 전에 필요한 준비물을 확인할 수 있었어요.`,
    '처음 가는 장소라 걱정했는데 위치와 전화번호가 같이 있어서 도움이 됐습니다.',
    '방문 전 운영시간을 한 번 더 확인하면 더 안전하게 이용할 수 있어요.',
  ]
}

function enrichPlaceReviews(place: Place, index: number) {
  const templates = placeReviewTemplates(place)
  const reviews = [...place.reviews, ...templates]
    .filter((review, reviewIndex, list) => list.indexOf(review) === reviewIndex)
    .slice(0, 4)
  return {
    ...place,
    reviews: reviews.length >= 3
      ? reviews
      : [...reviews, `최근 ${place.region} 이용자들이 확인한 생활도움 장소입니다.`].slice(0, 3 + (index % 2)),
  }
}

const rawPlaces: Place[] = Array.from({ length: 100 }, (_, index) => {
  const pending = index % 9 === 2
  const region = regions[index % regions.length]
  const coordinate = lifeMapCoordinate(region, index)
  return {
    id: index + 1,
    name: `${region.split(' ').at(-1)} ${placeCategories[index % placeCategories.length]} 장소 ${index + 1}`,
    category: placeCategories[index % placeCategories.length],
    region,
    address: `${region} 중심가 ${index + 10}`,
    phone: `0${index % 7 + 2}-0000-${String(1000 + index).slice(-4)}`,
    hours: ['평일 09:00 - 18:00', '월-토 10:00 - 17:00', '예약 후 방문', '매일 11:00 - 21:00'][index % 4],
    languages: index % 3 === 0 ? ['ko', 'en', 'vi'] : index % 3 === 1 ? ['ko', 'en'] : ['ko', 'vi'],
    reviews: [`${placeCategories[index % placeCategories.length]} 이용 안내가 도움이 됐어요.`],
    lat: coordinate.lat,
    lng: coordinate.lng,
    source: pending ? 'user' : 'operator',
    approvalStatus: pending ? 'pending' : 'approved',
    saved: index % 17 === 0,
    reviewHistory: pending ? ['사용자 장소 제보 접수', '관리자 검토 대기'] : ['운영자 등록', '연락처 확인 완료'],
  }
})

const denseForeignerAreaPlaces: Place[] = [
  {
    id: 201,
    name: '안산 원곡동 다문화마을특구',
    category: '외국인 밀집지역',
    region: '경기 안산',
    address: '경기 안산시 단원구 원곡동 다문화마을특구 일대',
    phone: '031-000-1130',
    hours: '상시 생활권 정보 확인',
    languages: ['ko', 'en', 'vi'],
    distanceKm: 0.6,
    isOpen: true,
    services: ['외국인 밀집 생활권', '다문화특구', '14개 언어 상담기관 인접'],
    foreignerFriendly: true,
    linkedFeedIds: [1],
    linkedPostIds: [1, 2],
    reviews: [
      '시·군·구 단위 외국인 주민 규모가 가장 큰 안산 생활권입니다.',
      '원곡동은 다문화마을특구와 외국인주민 상담 인프라가 함께 있는 상징 지역입니다.',
    ],
    lat: 37.3316,
    lng: 126.7948,
    source: 'operator',
    approvalStatus: 'approved',
    saved: true,
    reviewHistory: ['운영자 등록', '외국인 밀집지역 레이어 추가', '인구 약 11.3만명 기준 메모'],
  },
  {
    id: 202,
    name: '화성 제조업 외국인 근로자 생활권',
    category: '외국인 밀집지역',
    region: '경기 화성',
    address: '경기 화성시 향남·남양·마도 산업권 일대',
    phone: '031-000-8500',
    hours: '상시 생활권 정보 확인',
    languages: ['ko', 'en', 'vi'],
    distanceKm: 1.4,
    isOpen: true,
    services: ['외국인 밀집 생활권', '제조업 밀집', 'E-9 근로자 수요'],
    foreignerFriendly: true,
    linkedFeedIds: [],
    linkedPostIds: [2],
    reviews: ['제조업·중소기업 밀집으로 고용허가제 인력 수요가 큰 권역입니다.'],
    lat: 37.1995,
    lng: 126.8312,
    source: 'operator',
    approvalStatus: 'approved',
    saved: false,
    reviewHistory: ['운영자 등록', '외국인 주민 약 8.5만명 권역'],
  },
  {
    id: 203,
    name: '시흥 시화공단 외국인 근로 생활권',
    category: '외국인 밀집지역',
    region: '경기 시흥',
    address: '경기 시흥시 정왕동·시화공단 일대',
    phone: '031-000-8100',
    hours: '상시 생활권 정보 확인',
    languages: ['ko', 'en', 'vi'],
    distanceKm: 1.1,
    isOpen: true,
    services: ['외국인 밀집 생활권', '시화공단', '제조업'],
    foreignerFriendly: true,
    linkedFeedIds: [],
    linkedPostIds: [1],
    reviews: ['시화공단 중심의 제조업 생활권으로 외국인 근로자 이용 장소를 함께 확인하기 좋습니다.'],
    lat: 37.3452,
    lng: 126.7369,
    source: 'operator',
    approvalStatus: 'approved',
    saved: false,
    reviewHistory: ['운영자 등록', '외국인 주민 약 7.3~8.1만명 권역'],
  },
  {
    id: 204,
    name: '평택 산업단지 외국인 생활권',
    category: '외국인 밀집지역',
    region: '경기 평택',
    address: '경기 평택시 포승·송탄·고덕 산업권 일대',
    phone: '031-000-5100',
    hours: '상시 생활권 정보 확인',
    languages: ['ko', 'en'],
    distanceKm: 2.2,
    isOpen: true,
    services: ['외국인 밀집 생활권', '산업단지', '생활지원'],
    foreignerFriendly: true,
    linkedFeedIds: [],
    linkedPostIds: [],
    reviews: ['산업단지와 제조업 고용이 함께 있는 경기 남부 외국인 생활권입니다.'],
    lat: 36.9922,
    lng: 127.1128,
    source: 'operator',
    approvalStatus: 'approved',
    saved: false,
    reviewHistory: ['운영자 등록', '외국인 주민 약 5.1만명 권역'],
  },
  {
    id: 205,
    name: '서울 구로·대림 중국동포 생활권',
    category: '외국인 밀집지역',
    region: '서울 구로',
    address: '서울 구로구 구로동·대림역 생활권',
    phone: '02-000-5000',
    hours: '상시 생활권 정보 확인',
    languages: ['ko', 'en'],
    distanceKm: 0.9,
    isOpen: true,
    services: ['외국인 밀집 생활권', '중국동포 생활권', '생활상권'],
    foreignerFriendly: true,
    linkedFeedIds: [],
    linkedPostIds: [2],
    reviews: ['서울 서남권의 대표 외국인 밀집 생활권입니다. 금천·구로·영등포 비율도 함께 확인하면 좋습니다.'],
    lat: 37.4955,
    lng: 126.8877,
    source: 'operator',
    approvalStatus: 'approved',
    saved: false,
    reviewHistory: ['운영자 등록', '외국인 주민 약 5.0만명 권역'],
  },
  {
    id: 206,
    name: '서울 영등포 대림동 외국인 생활권',
    category: '외국인 밀집지역',
    region: '서울 영등포',
    address: '서울 영등포구 대림동 일대',
    phone: '02-000-4900',
    hours: '상시 생활권 정보 확인',
    languages: ['ko', 'en'],
    distanceKm: 0.8,
    isOpen: true,
    services: ['외국인 밀집 생활권', '대림동', '생활상권'],
    foreignerFriendly: true,
    linkedFeedIds: [],
    linkedPostIds: [2],
    reviews: ['대림동 중심의 외국인 생활상권과 커뮤니티 이용 수요가 높은 권역입니다.'],
    lat: 37.4933,
    lng: 126.8981,
    source: 'operator',
    approvalStatus: 'approved',
    saved: false,
    reviewHistory: ['운영자 등록', '외국인 주민 약 4.9만명 권역'],
  },
  {
    id: 207,
    name: '아산 제조업 외국인 근로 생활권',
    category: '외국인 밀집지역',
    region: '충남 아산',
    address: '충남 아산시 둔포·탕정·인주 산업권 일대',
    phone: '041-000-4200',
    hours: '상시 생활권 정보 확인',
    languages: ['ko', 'en', 'vi'],
    distanceKm: 3.4,
    isOpen: true,
    services: ['외국인 밀집 생활권', '제조업', '산업단지'],
    foreignerFriendly: true,
    linkedFeedIds: [],
    linkedPostIds: [],
    reviews: ['제조업 근로자가 많은 충남 북부 생활권으로 천안 서북구와 함께 확인하면 좋습니다.'],
    lat: 36.7898,
    lng: 127.0019,
    source: 'operator',
    approvalStatus: 'approved',
    saved: false,
    reviewHistory: ['운영자 등록', '외국인 주민 약 4.2만명 권역'],
  },
  {
    id: 208,
    name: '김해 제조업 외국인 생활권',
    category: '외국인 밀집지역',
    region: '경남 김해',
    address: '경남 김해시 진영·주촌·한림 제조업 권역',
    phone: '055-000-3300',
    hours: '상시 생활권 정보 확인',
    languages: ['ko', 'en', 'vi'],
    distanceKm: 1.7,
    isOpen: true,
    services: ['외국인 밀집 생활권', '제조업', '생활상담'],
    foreignerFriendly: true,
    linkedFeedIds: [1],
    linkedPostIds: [],
    reviews: ['경남 제조업 권역의 대표 외국인 근로자 생활권입니다.'],
    lat: 35.2285,
    lng: 128.8893,
    source: 'operator',
    approvalStatus: 'approved',
    saved: false,
    reviewHistory: ['운영자 등록', '외국인 주민 약 3.3만명 권역'],
  },
  {
    id: 209,
    name: '김포 산업권 외국인 생활권',
    category: '외국인 밀집지역',
    region: '경기 김포',
    address: '경기 김포시 양촌·대곶 산업권 일대',
    phone: '031-000-3309',
    hours: '상시 생활권 정보 확인',
    languages: ['ko', 'en'],
    distanceKm: 2.6,
    isOpen: true,
    services: ['외국인 밀집 생활권', '제조업', '생활정보'],
    foreignerFriendly: true,
    linkedFeedIds: [],
    linkedPostIds: [],
    reviews: ['서울 서북권과 경기 서부 산업권을 잇는 외국인 근로자 생활권입니다.'],
    lat: 37.6152,
    lng: 126.7156,
    source: 'operator',
    approvalStatus: 'approved',
    saved: false,
    reviewHistory: ['운영자 등록', '외국인 주민 약 3.3만명 권역'],
  },
  {
    id: 210,
    name: '인천 부평 외국인 생활권',
    category: '외국인 밀집지역',
    region: '인천 부평',
    address: '인천 부평구 부평·십정 생활권 일대',
    phone: '032-000-3100',
    hours: '상시 생활권 정보 확인',
    languages: ['ko', 'en'],
    distanceKm: 1.5,
    isOpen: true,
    services: ['외국인 밀집 생활권', '생활상권', '교통 접근'],
    foreignerFriendly: true,
    linkedFeedIds: [],
    linkedPostIds: [],
    reviews: ['인천 내 외국인 주민 규모가 큰 생활권으로 교통 접근성이 좋습니다.'],
    lat: 37.5070,
    lng: 126.7218,
    source: 'operator',
    approvalStatus: 'approved',
    saved: false,
    reviewHistory: ['운영자 등록', '외국인 주민 약 3.1만명 권역'],
  },
  {
    id: 211,
    name: '대구 달서 성서산단 외국인 생활권',
    category: '외국인 밀집지역',
    region: '대구 달서',
    address: '대구 달서구 성서산업단지·이곡동 생활권 일대',
    phone: '053-000-2800',
    hours: '상시 생활권 정보 확인',
    languages: ['ko', 'en', 'vi'],
    distanceKm: 2.1,
    isOpen: true,
    services: ['외국인 밀집 생활권', '산업단지', '생활상권'],
    foreignerFriendly: true,
    linkedFeedIds: [],
    linkedPostIds: [],
    reviews: ['성서산단과 주변 생활상권을 중심으로 외국인 근로자 이용 수요가 있는 권역입니다.'],
    lat: 35.8562,
    lng: 128.4919,
    source: 'operator',
    approvalStatus: 'approved',
    saved: false,
    reviewHistory: ['운영자 등록', '영남권 대표 외국인 생활권 보강'],
  },
  {
    id: 212,
    name: '경북 경산 제조업·대학 외국인 생활권',
    category: '외국인 밀집지역',
    region: '경북 경산',
    address: '경북 경산시 진량·하양·대학가 생활권 일대',
    phone: '053-000-2400',
    hours: '상시 생활권 정보 확인',
    languages: ['ko', 'en', 'vi'],
    distanceKm: 2.4,
    isOpen: true,
    services: ['외국인 밀집 생활권', '제조업', '유학생 생활권'],
    foreignerFriendly: true,
    linkedFeedIds: [],
    linkedPostIds: [],
    reviews: ['제조업과 대학 생활권이 함께 있어 일자리·생활정보 수요가 겹치는 지역입니다.'],
    lat: 35.8251,
    lng: 128.7415,
    source: 'operator',
    approvalStatus: 'approved',
    saved: false,
    reviewHistory: ['운영자 등록', '경북 외국인 생활권 보강'],
  },
  {
    id: 213,
    name: '부산 사상·녹산 산업권 외국인 생활권',
    category: '외국인 밀집지역',
    region: '부산 사상',
    address: '부산 사상구·강서구 녹산산단 생활권 일대',
    phone: '051-000-2600',
    hours: '상시 생활권 정보 확인',
    languages: ['ko', 'en', 'vi'],
    distanceKm: 2.8,
    isOpen: true,
    services: ['외국인 밀집 생활권', '산업단지', '항만·제조업'],
    foreignerFriendly: true,
    linkedFeedIds: [],
    linkedPostIds: [],
    reviews: ['부산 서부 산업권과 생활상권을 함께 확인할 수 있는 대표 권역입니다.'],
    lat: 35.1527,
    lng: 128.9914,
    source: 'operator',
    approvalStatus: 'approved',
    saved: false,
    reviewHistory: ['운영자 등록', '부산권 대표 마커 보강'],
  },
  {
    id: 214,
    name: '전북 익산·군산 제조업 외국인 생활권',
    category: '외국인 밀집지역',
    region: '전북 익산',
    address: '전북 익산시·군산 산업권 생활권 일대',
    phone: '063-000-2300',
    hours: '상시 생활권 정보 확인',
    languages: ['ko', 'en', 'vi'],
    distanceKm: 2.9,
    isOpen: true,
    services: ['외국인 밀집 생활권', '산업단지', '농공단지'],
    foreignerFriendly: true,
    linkedFeedIds: [],
    linkedPostIds: [],
    reviews: ['전북 서북부 제조업·농공단지 생활권을 대표하는 외국인 근로자 권역입니다.'],
    lat: 35.9483,
    lng: 126.9576,
    source: 'operator',
    approvalStatus: 'approved',
    saved: false,
    reviewHistory: ['운영자 등록', '전북권 대표 마커 보강'],
  },
  {
    id: 215,
    name: '전남 광주·광산산단 외국인 생활권',
    category: '외국인 밀집지역',
    region: '전남 광주',
    address: '광주 광산구 하남산단·평동산단 생활권 일대',
    phone: '062-000-2200',
    hours: '상시 생활권 정보 확인',
    languages: ['ko', 'en', 'vi'],
    distanceKm: 2.7,
    isOpen: true,
    services: ['외국인 밀집 생활권', '산업단지', '생활상담'],
    foreignerFriendly: true,
    linkedFeedIds: [],
    linkedPostIds: [],
    reviews: ['광주 광산권 산업단지와 생활상권을 중심으로 외국인 근로자 이용 수요가 있습니다.'],
    lat: 35.1595,
    lng: 126.8526,
    source: 'operator',
    approvalStatus: 'approved',
    saved: false,
    reviewHistory: ['운영자 등록', '호남권 대표 마커 보강'],
  },
  {
    id: 216,
    name: '제주 농업·관광업 외국인 생활권',
    category: '외국인 밀집지역',
    region: '제주 제주시',
    address: '제주시·서귀포 농업 및 관광업 생활권 일대',
    phone: '064-000-2100',
    hours: '상시 생활권 정보 확인',
    languages: ['ko', 'en', 'vi'],
    distanceKm: 3.1,
    isOpen: true,
    services: ['외국인 밀집 생활권', '농업', '관광업'],
    foreignerFriendly: true,
    linkedFeedIds: [],
    linkedPostIds: [],
    reviews: ['농업·관광업 계절 수요가 있어 생활지도에서 별도 권역으로 확인할 필요가 있습니다.'],
    lat: 33.4996,
    lng: 126.5312,
    source: 'operator',
    approvalStatus: 'approved',
    saved: false,
    reviewHistory: ['운영자 등록', '제주권 대표 마커 보강'],
  },
]

const generatedPlaces: Place[] = (rawPlaces.map((place, index) => ({
  ...place,
  name: `${place.region.split(' ').at(-1)} ${lifeMapCategories[index % lifeMapCategories.length]} 도움처 ${index + 1}`,
  category: lifeMapCategories[index % lifeMapCategories.length],
  distanceKm: Number((0.4 + (index % 18) * 0.35).toFixed(1)),
  isOpen: index % 4 !== 2,
  services: lifeMapServices[index % lifeMapServices.length],
  foreignerFriendly: index % 5 !== 3,
  linkedFeedIds: index % 4 === 0 ? [index + 1] : [],
  linkedPostIds: index % 6 === 0 ? [index + 1] : [],
  reviews: [
    `${lifeMapCategories[index % lifeMapCategories.length]} 이용 안내가 도움이 됐어요.`,
    index % 5 === 0 ? '처음 방문해도 접수 방법을 천천히 알려줬어요.' : '전화로 운영시간을 확인하고 방문하는 것이 좋아요.',
  ],
})) as Place[]).concat(denseForeignerAreaPlaces, {
  id: 101,
  name: '오창 외국인 노동상담센터',
  category: '상담기관',
  region: '충북 청주',
  address: '충북 청주시 청원구 오창읍 중심상업로 24',
  phone: '043-000-1120',
  hours: '평일 09:00 - 18:00',
  languages: ['ko', 'en', 'vi'],
  distanceKm: 0.8,
  isOpen: true,
  services: ['노동상담', '통역 연결', '체류·임금 안내'],
  foreignerFriendly: true,
  linkedFeedIds: [3],
  linkedPostIds: [1],
  reviews: [
    '임금이나 계약 문제를 한국어가 서툴러도 차근차근 안내받을 수 있어요.',
    '방문 전 전화로 상담 가능 언어와 시간을 확인하는 것이 좋아요.',
  ],
  lat: 36.713,
  lng: 127.429,
  mapX: 73,
  mapY: 57,
  source: 'operator',
  approvalStatus: 'approved',
  saved: false,
  reviewHistory: ['운영자 등록', '외국인 친화 상담기관으로 표시'],
}, ...([
  {
    id: 102,
    name: '충북도청 민원실',
    category: '행정기관',
    region: '충북 청주',
    address: '충북 청주시 상당구 상당로 82',
    phone: '043-220-2114',
    hours: '평일 09:00 - 18:00',
    languages: ['ko'],
    distanceKm: 0.1,
    isOpen: true,
    services: ['민원 안내', '생활 행정', '외국인 체류 서류 확인'],
    foreignerFriendly: true,
    linkedFeedIds: [],
    linkedPostIds: [],
    reviews: ['충북도청 기준 현재 위치 마커입니다. 방문 전 담당 부서를 확인하세요.'],
    lat: 36.6356,
    lng: 127.4914,
    mapX: 51,
    mapY: 52,
    directionsUrl: 'https://map.kakao.com/link/to/%EC%B6%A9%EB%B6%81%EB%8F%84%EC%B2%AD%20%EB%AF%BC%EC%9B%90%EC%8B%A4,36.6356,127.4914',
    source: 'operator',
    approvalStatus: 'approved',
    saved: true,
    reviewHistory: ['운영자 등록', '현재 위치 기준점으로 표시'],
  },
  {
    id: 103,
    name: '청주 외국인주민 지원 안내',
    category: '상담기관',
    region: '충북 청주',
    address: '충북 청주시 상당구 상당로 82 주변',
    phone: '043-000-1330',
    hours: '평일 10:00 - 17:00',
    languages: ['ko', 'en', 'vi'],
    distanceKm: 0.4,
    isOpen: true,
    services: ['생활상담', '기관 연결', '통역 안내'],
    foreignerFriendly: true,
    linkedFeedIds: [1],
    linkedPostIds: [2],
    reviews: ['처음 문의할 때 한국어가 어려우면 통역 가능 여부를 먼저 확인하세요.'],
    lat: 36.6371,
    lng: 127.4896,
    mapX: 48,
    mapY: 50,
    directionsUrl: 'https://map.kakao.com/link/to/%EC%B2%AD%EC%A3%BC%20%EC%99%B8%EA%B5%AD%EC%9D%B8%EC%A3%BC%EB%AF%BC%20%EC%A7%80%EC%9B%90%20%EC%95%88%EB%82%B4,36.6371,127.4896',
    source: 'operator',
    approvalStatus: 'approved',
    saved: false,
    reviewHistory: ['운영자 추천', '충북도청 주변 상담 안내'],
  },
  {
    id: 104,
    name: '청주 상당구 보건소',
    category: '병원',
    region: '충북 청주',
    address: '충북 청주시 상당구 남일면 단재로 480',
    phone: '043-201-3114',
    hours: '평일 09:00 - 18:00',
    languages: ['ko', 'en'],
    distanceKm: 2.8,
    isOpen: true,
    services: ['기초 진료 안내', '예방접종', '건강 상담'],
    foreignerFriendly: true,
    linkedFeedIds: [],
    linkedPostIds: [3],
    reviews: ['외국인 등록 여부와 보험 적용 여부를 방문 전 확인하는 것이 좋아요.'],
    lat: 36.6098,
    lng: 127.5044,
    mapX: 58,
    mapY: 66,
    directionsUrl: 'https://map.kakao.com/link/to/%EC%B2%AD%EC%A3%BC%20%EC%83%81%EB%8B%B9%EA%B5%AC%20%EB%B3%B4%EA%B1%B4%EC%86%8C,36.6098,127.5044',
    source: 'operator',
    approvalStatus: 'approved',
    saved: false,
    reviewHistory: ['운영자 등록', '공공 보건기관'],
  },
  {
    id: 105,
    name: '성안길 가까운 약국 안내',
    category: '약국',
    region: '충북 청주',
    address: '충북 청주시 상당구 성안로 일대',
    phone: '043-000-1205',
    hours: '월-토 09:00 - 20:00',
    languages: ['ko'],
    distanceKm: 0.7,
    isOpen: true,
    services: ['일반의약품', '복약 안내', '병원 처방 조제'],
    foreignerFriendly: false,
    linkedFeedIds: [],
    linkedPostIds: [],
    reviews: ['증상 사진이나 번역 앱을 준비하면 약 상담이 더 수월합니다.'],
    lat: 36.6344,
    lng: 127.4886,
    mapX: 47,
    mapY: 54,
    directionsUrl: 'https://map.kakao.com/link/to/%EC%84%B1%EC%95%88%EA%B8%B8%20%EA%B0%80%EA%B9%8C%EC%9A%B4%20%EC%95%BD%EA%B5%AD%20%EC%95%88%EB%82%B4,36.6344,127.4886',
    source: 'operator',
    approvalStatus: 'approved',
    saved: false,
    reviewHistory: ['운영자 등록', '도청 주변 생활 약국 안내'],
  },
  {
    id: 106,
    name: '청주 고속버스터미널 송금/환전 안내',
    category: '송금/은행',
    region: '충북 청주',
    address: '충북 청주시 흥덕구 풍산로 15 주변',
    phone: '043-000-1606',
    hours: '평일 09:30 - 16:00',
    languages: ['ko', 'en'],
    distanceKm: 4.6,
    isOpen: true,
    services: ['해외송금', 'ATM', '환전 상담'],
    foreignerFriendly: true,
    linkedFeedIds: [],
    linkedPostIds: [],
    reviews: ['송금 수수료와 신분증 지참 여부를 먼저 확인하세요.'],
    lat: 36.6267,
    lng: 127.4313,
    mapX: 25,
    mapY: 57,
    directionsUrl: 'https://map.kakao.com/link/to/%EC%B2%AD%EC%A3%BC%20%EA%B3%A0%EC%86%8D%EB%B2%84%EC%8A%A4%ED%84%B0%EB%AF%B8%EB%84%90%20%EC%86%A1%EA%B8%88%2F%ED%99%98%EC%A0%84%20%EC%95%88%EB%82%B4,36.6267,127.4313',
    source: 'operator',
    approvalStatus: 'approved',
    saved: false,
    reviewHistory: ['운영자 등록', '터미널 생활권 송금 안내'],
  },
  {
    id: 107,
    name: '오창산단 외국인 근로 상담 포인트',
    category: '상담기관',
    region: '충북 청주',
    address: '충북 청주시 청원구 오창읍 과학산업단지 주변',
    phone: '043-000-1707',
    hours: '예약 후 방문',
    languages: ['ko', 'en', 'vi'],
    distanceKm: 12.4,
    isOpen: false,
    services: ['노동상담', '기숙사 문제', '임금체불 안내'],
    foreignerFriendly: true,
    linkedFeedIds: [1],
    linkedPostIds: [1],
    reviews: ['오창 산단 근무자는 근무지 주소와 계약서를 준비하면 상담이 빠릅니다.'],
    lat: 36.7161,
    lng: 127.4237,
    mapX: 72,
    mapY: 42,
    directionsUrl: 'https://map.kakao.com/link/to/%EC%98%A4%EC%B0%BD%EC%82%B0%EB%8B%A8%20%EC%99%B8%EA%B5%AD%EC%9D%B8%20%EA%B7%BC%EB%A1%9C%20%EC%83%81%EB%8B%B4%20%ED%8F%AC%EC%9D%B8%ED%8A%B8,36.7161,127.4237',
    source: 'operator',
    approvalStatus: 'approved',
    saved: false,
    reviewHistory: ['운영자 추천', '오창산단 외국인 근로자 생활권'],
  },
  {
    id: 108,
    name: '음성 금왕 외국인 생활상담',
    category: '상담기관',
    region: '충북 음성',
    address: '충북 음성군 금왕읍 무극로 일대',
    phone: '043-000-1808',
    hours: '평일 10:00 - 17:00',
    languages: ['ko', 'vi'],
    distanceKm: 31.2,
    isOpen: true,
    services: ['생활상담', '한국어 안내', '고용센터 연결'],
    foreignerFriendly: true,
    linkedFeedIds: [1],
    linkedPostIds: [],
    reviews: ['음성 농업·제조 현장 근로자가 자주 찾는 생활상담 권역입니다.'],
    lat: 36.9917,
    lng: 127.5962,
    mapX: 66,
    mapY: 25,
    directionsUrl: 'https://map.kakao.com/link/to/%EC%9D%8C%EC%84%B1%20%EA%B8%88%EC%99%95%20%EC%99%B8%EA%B5%AD%EC%9D%B8%20%EC%83%9D%ED%99%9C%EC%83%81%EB%8B%B4,36.9917,127.5962',
    source: 'operator',
    approvalStatus: 'approved',
    saved: false,
    reviewHistory: ['운영자 등록', '충북 음성 권역 보강'],
  },
  {
    id: 109,
    name: '진천 외국인 도움 행정 안내',
    category: '행정기관',
    region: '충북 진천',
    address: '충북 진천군 진천읍 상산로 13 주변',
    phone: '043-000-1909',
    hours: '평일 09:00 - 18:00',
    languages: ['ko'],
    distanceKm: 24.8,
    isOpen: true,
    services: ['전입 안내', '민원 서류', '기관 연결'],
    foreignerFriendly: true,
    linkedFeedIds: [],
    linkedPostIds: [],
    reviews: ['진천 지역 근로자는 청주와 함께 확인하면 이동 동선 잡기가 편합니다.'],
    lat: 36.8554,
    lng: 127.4356,
    mapX: 43,
    mapY: 32,
    directionsUrl: 'https://map.kakao.com/link/to/%EC%A7%84%EC%B2%9C%20%EC%99%B8%EA%B5%AD%EC%9D%B8%20%EB%8F%84%EC%9B%80%20%ED%96%89%EC%A0%95%20%EC%95%88%EB%82%B4,36.8554,127.4356',
    source: 'operator',
    approvalStatus: 'approved',
    saved: false,
    reviewHistory: ['운영자 등록', '충북 진천 권역 보강'],
  },
] as Place[]))
export const places: Place[] = generatedPlaces.map(enrichPlaceReviews)

export const placeReports: PlaceReport[] = places
  .filter((place) => place.source === 'user')
  .slice(0, 12)
  .map((place, index) => ({
    id: index + 1,
    placeId: place.id,
    reporter: authors[index % authors.length],
    status: place.approvalStatus,
    memo: '사진, 전화번호, 운영시간 확인 후 지도 노출 여부 결정',
  }))

export const initialDailyFeeds: DailyFeed[] = Array.from({ length: 50 }, (_, index) => {
  const category = categories[index % categories.length]
  const firstFeedImage = '/mock/daily/e9-farm-workers-happy.png'
  const secondFeedImage = '/mock/daily/2026-06-04%20162831.png'
  const thirdFeedImage = '/mock/daily/10224171-f0fa-492b-a6ae-10a577d48179.png'
  const body =
    index % 11 === 1
      ? '회사생활 질문입니다. 잔업 시간이 급여명세서에 다르게 적힌 것 같아 임금 문제 상담이 필요합니다.'
      : index % 13 === 2
        ? '처음 보는 사람이 여권 보관을 요구해서 조심하세요. 도움 요청 기록을 남기는 것이 좋겠습니다.'
        : `${regions[index % regions.length]}에서 ${category} 경험을 공유합니다. 생활지도와 커뮤니티에 연결해두면 다음에 찾기 쉬워요.`
  return {
    id: index + 1,
    image: index === 0 ? firstFeedImage : index === 1 ? secondFeedImage : index === 2 ? thirdFeedImage : `https://picsum.photos/seed/workhere-daily-${index + 1}/900/620`,
    images: index === 0
      ? [{ id: 1, url: firstFeedImage, alt: 'E-9 farm workers smiling on the way to the field' }]
      : index === 1
        ? [{ id: 1, url: secondFeedImage, alt: 'Foreign workers gathering together at a labor rally' }]
        : index === 2
          ? [{ id: 1, url: thirdFeedImage, alt: 'A disappointing cafeteria meal served to foreign workers' }]
      : Array.from({ length: index % 7 === 0 ? 4 : index % 5 === 0 ? 3 : 1 }, (_, imageIndex) => ({
        id: imageIndex + 1,
        url: `https://picsum.photos/seed/workhere-daily-${index + 1}-${imageIndex + 1}/900/1125`,
        alt: `${authors[index % authors.length]} daily photo ${imageIndex + 1}`,
      })),
    author: index === 0 ? 'Tuan Nguyen' : index === 1 ? 'Aziz Karimov' : index === 2 ? 'Linh Pham' : authors[index % authors.length],
    ...sampleUserFields(index),
    ...(index === 0 ? {
      authorId: 2,
      displayName: 'Tuan Nguyen',
      username: 'tuan.farm.e9',
      avatarUrl: '/mock/avatars/processed/avatar-002.webp',
      countryCode: 'VN',
      countryName: '베트남',
      flagIconUrl: '/flags/vn.svg',
      flagEmoji: '🇻🇳',
      isCountryVerified: true,
      isVerified: true,
      verificationStatus: 'verified' as const,
      preferredLanguage: 'vi' as const,
      gradientColors: ['#DA251D', '#FFCD00'],
    } : {}),
    ...(index === 1 ? {
      authorId: 7,
      displayName: 'Aziz Karimov',
      username: 'aziz.e9.voice',
      avatarUrl: '/mock/avatars/processed/avatar-019.webp',
      countryCode: 'UZ',
      countryName: '우즈베키스탄',
      flagIconUrl: '/flags/uz.svg',
      flagEmoji: '🇺🇿',
      isCountryVerified: true,
      isVerified: true,
      verificationStatus: 'verified' as const,
      preferredLanguage: 'en' as const,
      gradientColors: ['#1EB5E5', '#009B5A'],
    } : {}),
    ...(index === 2 ? {
      authorId: 3,
      displayName: 'Linh Pham',
      username: 'linh.food',
      avatarUrl: '/mock/avatars/processed/avatar-007.webp',
      countryCode: 'VN',
      countryName: '베트남',
      flagIconUrl: '/flags/vn.svg',
      flagEmoji: '🇻🇳',
      isCountryVerified: false,
      isVerified: false,
      verificationStatus: 'unverified' as const,
      preferredLanguage: 'vi' as const,
      gradientColors: ['#94A3B8', '#CBD5E1'],
    } : {}),
    nationality: index === 0 ? 'Vietnam' : index === 1 ? 'Uzbekistan' : index === 2 ? 'Vietnam' : nationalities[index % nationalities.length],
    region: index === 0 ? '충북 음성' : index === 1 ? '서울 광화문' : index === 2 ? '경기 안산' : regions[index % regions.length],
    createdAt: index < 9 ? `오늘 ${9 + index}:20` : `${index % 6 + 1}일 전`,
    body: index === 0 ? '아침에 농장으로 가는 길, 트럭 뒤에서 다 같이 손 흔들고 웃었어요. 오늘은 고추밭 정리하는 날이라 땀이 많이 났지만 팀 분위기가 좋아서 힘이 납니다. E-9로 한국에서 일하는 하루하루가 쉽지만은 않지만, 이렇게 웃는 얼굴 하나면 밭도 조금 더 넓게, 마음도 조금 더 가볍게 느껴져요. 오늘도 안전하게 일하고 맛있는 점심 먹자!' : index === 1 ? '자~~ 드가자! 오늘은 외국인 노동자 친구들과 함께 목소리 내는 날. 서로 안전하게 챙기고, 끝나고 따뜻한 밥 먹자!' : index === 2 ? '이건 아니지 말입니다!! 오늘 급식 보고 다 같이 조용해졌어요. 바쁜 날일수록 밥이라도 든든해야 힘이 나는데, 다음에는 조금만 더 신경 써주면 좋겠습니다.' : body,
    translatedBody: index === 0 ? 'On the way to the farm this morning, everyone smiled and waved from the truck. Work is not always easy, but a cheerful team makes the day feel lighter. Stay safe and enjoy lunch!' : index === 1 ? 'Let’s go! Today we stand together with foreign worker friends. Take care of each other, and let’s eat a warm meal after the rally.' : index === 2 ? 'This is really not okay! Everyone got quiet after seeing today’s cafeteria meal. On busy workdays, a proper meal matters. I hope it gets better next time.' : `Shared daily life information in ${regions[index % regions.length]}.`,
    category: index === 1 ? '회사생활' : index === 2 ? '음식' : category,
    hashtags: index === 0 ? ['#E9', '#농장일', '#충북음성', '#베트남인증', '#출근길', '#웃는하루', '#안전제일'] : index === 1 ? ['#외국인노동자', '#집회현장', '#노동권', '#함께가자', '#자드가자', '#안전하게'] : index === 2 ? ['#급식', '#식사개선', '#회사생활', '#기숙사생활', '#오늘밥', '#이건아니지말입니다'] : [`#${regions[index % regions.length].split(' ').at(-1)}`, `#${category}`, index % 5 === 0 ? '#생활정보' : '#기록'],
    placeId: index % 4 === 0 ? (index % places.length) + 1 : undefined,
    jobId: index === 1 ? 1 : category === '회사생활' ? (index % jobs.length) + 1 : undefined,
    likes: 6 + ((index * 7) % 90),
    comments: index === 1 ? ['응원합니다. 안전하게 다녀오세요.'] : index === 2 ? ['이건 진짜 개선이 필요해 보여요.'] : [`${regions[index % regions.length]} 정보 감사합니다.`],
    saved: index % 10 === 0,
    reported: index === 1 || index === 2 ? 0 : index % 11 === 1 || index % 13 === 2 ? 2 : index % 8 === 0 ? 1 : 0,
    visibility: index === 1 ? 'public' : index % 5 === 0 ? 'nationality' : index % 4 === 0 ? 'region' : 'public',
    hidden: index !== 0 && index % 29 === 0,
  }
})

export const feedImages: FeedImage[] = initialDailyFeeds.map((feed) => ({ id: feed.id, feedId: feed.id, url: feed.image }))

export const feedLikes: FeedLike[] = Array.from({ length: 140 }, (_, index) => ({
  id: index + 1,
  feedId: (index % initialDailyFeeds.length) + 1,
  userId: (index % users.length) + 1,
}))

export const feedComments: FeedComment[] = initialDailyFeeds.map((feed, index) => ({
  id: index + 1,
  feedId: feed.id,
  author: authors[(index + 2) % authors.length],
  authorId: Number(sampleUsers[(index + 2) % sampleUsers.length].id),
  body: feed.comments[0],
  reported: index % 12 === 0 ? 1 : 0,
}))

const relatableCommunityPosts: Post[] = [
  {
    id: 1,
    groupId: 'e9-workers',
    boardId: 'free',
    title: '퇴근하고 방에 오면 말이 없어지는 날 있나요',
    author: 'Tuan',
    ...sampleUserFields(3),
    category: '공감',
    body: '일할 때는 괜찮은 척하는데 기숙사 방에 들어오면 갑자기 조용해지는 날이 있어요. 가족한테 전화하면 걱정할까 봐 웃으면서 말합니다. 그래도 여기서 같은 마음 보는 것만으로 조금 힘이 납니다.',
    languageCode: 'ko',
    originalLanguage: '한국어',
    translatedText: '번역 미리보기: 퇴근 후 외로움과 가족에게 걱정을 숨기는 마음을 나누는 글입니다.',
    likeCount: 86,
    commentCount: 9,
    viewCount: 612,
    saved: true,
    comments: ['저도 그래요. 그래서 일요일마다 친구랑 같이 밥 먹기로 했어요.', '가족한테는 항상 괜찮다고 말하게 되죠. 여기서라도 편하게 말해요.', '오늘 하루도 고생했어요. 따뜻한 밥 꼭 챙기세요.'],
    reported: 0,
    images: [],
  },
  {
    id: 2,
    groupId: 'cheongju-life',
    boardId: 'free',
    title: '한국 겨울 출근길 장갑 추천해주세요',
    author: 'Mina',
    ...sampleUserFields(4),
    category: '생활질문',
    body: '아침 6시에 버스 기다리면 손이 너무 시려요. 작업 장갑 말고 출퇴근 때 낄 수 있는 따뜻한 장갑 추천 있나요? 다이소, 마트에서 살 수 있으면 더 좋아요.',
    languageCode: 'ko',
    originalLanguage: '한국어',
    translatedText: '번역 미리보기: 추운 겨울 출근길에 쓸 장갑 추천을 묻는 생활 질문입니다.',
    likeCount: 42,
    commentCount: 7,
    viewCount: 388,
    comments: ['스마트폰 터치 되는 기모 장갑 좋아요. 다이소에도 있어요.', '목도리보다 귀마개가 진짜 중요해요. 바람이 너무 차요.', '편의점 핫팩도 같이 사면 버스 기다릴 때 좋아요.'],
    reported: 0,
    images: [],
  },
  {
    id: 3,
    groupId: 'ansan-vn',
    boardId: 'workplace',
    title: '급식에 고향 음식 생각나는 날',
    author: 'Linh',
    ...sampleUserFields(6),
    category: '회사생활',
    body: '오늘 점심에 국이 너무 매워서 밥만 많이 먹었어요. 한국 음식 적응 중인데 가끔은 고향 음식이 너무 생각납니다. 다들 회사 밥 힘들 때 어떻게 하세요?',
    languageCode: 'ko',
    originalLanguage: '한국어',
    translatedText: '번역 미리보기: 회사 급식과 고향 음식이 그리운 마음을 나누는 글입니다.',
    likeCount: 73,
    commentCount: 11,
    viewCount: 534,
    comments: ['저는 주말에 친구들이랑 쌀국수 만들어 먹어요.', '매운 음식 힘들면 김이랑 계란 챙겨가면 좋아요.', '회사에 알레르기나 못 먹는 음식은 말해도 괜찮아요.'],
    reported: 0,
    images: [],
  },
  {
    id: 4,
    groupId: 'national-safety',
    boardId: 'help',
    title: '월급날 전날부터 계속 계산기 두드리는 사람',
    author: 'Ali',
    ...sampleUserFields(7),
    category: '급여공감',
    body: '월급 들어오기 전날이면 이번 달 송금, 방세, 교통비, 휴대폰 요금 계산하느라 머리가 복잡합니다. 그래도 가족한테 보낼 돈 먼저 생각하게 되네요. 다들 생활비 관리 어떻게 하세요?',
    languageCode: 'ko',
    originalLanguage: '한국어',
    translatedText: '번역 미리보기: 월급과 송금, 생활비 관리에 대한 공감 글입니다.',
    isSafetyReport: true,
    likeCount: 95,
    commentCount: 13,
    viewCount: 721,
    saved: true,
    comments: ['저는 월급 들어오면 바로 송금액부터 따로 빼요.', '급여명세서 사진 꼭 저장하세요. 나중에 확인할 때 필요해요.', '가계부 앱보다 메모장에 고정비 먼저 적는 게 편했어요.'],
    reported: 0,
    images: [],
  },
  {
    id: 5,
    groupId: 'changwon-uz',
    boardId: 'free',
    title: '쉬는 날 하루가 너무 빨리 지나가요',
    author: 'Rafi',
    ...sampleUserFields(8),
    category: '쉬는날',
    body: '빨래하고 장보고 방 청소하면 쉬는 날이 끝나요. 쉬는 날도 쉬는 느낌이 별로 없네요. 그래도 친구랑 카페 가서 한국어 공부 조금 하면 기분이 좋아집니다.',
    languageCode: 'ko',
    originalLanguage: '한국어',
    translatedText: '번역 미리보기: 쉬는 날이 금방 지나가는 외국인 근로자의 일상 공감 글입니다.',
    likeCount: 64,
    commentCount: 8,
    viewCount: 402,
    comments: ['맞아요. 쉬는 날은 왜 이렇게 짧을까요.', '저는 빨래는 금요일 밤에 하고 일요일은 밖에 나가요.', '같이 공부하는 친구 있으면 진짜 도움이 됩니다.'],
    reported: 0,
    images: [],
  },
  {
    id: 6,
    groupId: 'e9-workers',
    boardId: 'qna',
    title: '병원 갈 때 증상 설명이 제일 어려워요',
    author: 'Sara',
    ...sampleUserFields(9),
    category: 'Q&A',
    body: '감기나 허리 통증은 말하기 쉬운데 속이 답답하다, 어지럽다 같은 말은 병원에서 설명하기 어렵습니다. 병원 가기 전에 번역 앱에 어떤 문장 준비하면 좋을까요?',
    languageCode: 'ko',
    originalLanguage: '한국어',
    translatedText: '번역 미리보기: 병원에서 증상을 설명하기 어려운 상황에 대한 질문입니다.',
    likeCount: 58,
    commentCount: 10,
    viewCount: 476,
    comments: ['언제부터 아픈지, 어디가 아픈지, 열이 있는지 먼저 적어가세요.', '약 알레르기 있으면 꼭 번역해서 보여주세요.', '사진으로 증상 메모해두면 접수할 때 편해요.'],
    reported: 0,
    images: [],
  },
  {
    id: 7,
    groupId: 'hwaseong-cn',
    boardId: 'workplace',
    title: '한국어를 알아듣고 웃었는데 칭찬받았어요',
    author: 'Grace',
    ...sampleUserFields(10),
    category: '자랑/축하',
    body: '반장님이 농담한 말을 처음으로 알아듣고 같이 웃었어요. 별거 아닌데 오늘 하루 기분이 좋았습니다. 한국어 공부 조금씩 해도 언젠가 들리네요.',
    languageCode: 'ko',
    originalLanguage: '한국어',
    translatedText: '번역 미리보기: 한국어가 조금씩 들리기 시작한 기쁜 순간을 나누는 글입니다.',
    likeCount: 101,
    commentCount: 12,
    viewCount: 688,
    comments: ['축하해요! 그 순간 진짜 기분 좋아요.', '저도 처음 택배 기사님 말 알아들었을 때 뿌듯했어요.', '조금씩 하면 정말 늘어요. 같이 힘내요.'],
    reported: 0,
    images: [],
  },
  {
    id: 8,
    groupId: 'cheongju-life',
    boardId: 'market',
    title: '기숙사에서 같이 먹는 라면이 제일 맛있을 때',
    author: 'Somchai',
    ...sampleUserFields(11),
    category: '숙소생활',
    body: '야근 끝나고 돌아와서 친구들이랑 라면 끓여 먹으면 이상하게 제일 맛있어요. 피곤하지만 같이 웃는 시간이 있어서 버티는 것 같습니다.',
    languageCode: 'ko',
    originalLanguage: '한국어',
    translatedText: '번역 미리보기: 야근 후 기숙사에서 친구들과 먹는 라면에 대한 공감 글입니다.',
    likeCount: 88,
    commentCount: 9,
    viewCount: 519,
    comments: ['계란 하나 넣으면 하루 피로가 조금 풀려요.', '기숙사 라면 냄새 나면 다 모입니다.', '맞아요. 같이 먹는 사람이 있으면 힘이 나요.'],
    reported: 0,
    images: [],
  },
  {
    id: 9,
    groupId: 'national-safety',
    boardId: 'safety',
    title: '새로 온 친구에게 꼭 말해주는 것',
    author: 'Nika',
    ...sampleUserFields(12),
    category: '조심하세요',
    body: '처음 한국 온 친구들에게 항상 말합니다. 계약서 사진 저장하기, 급여명세서 버리지 않기, 모르는 수수료 요구하면 바로 물어보기. 작은 기록이 나중에 큰 도움이 됩니다.',
    languageCode: 'ko',
    originalLanguage: '한국어',
    translatedText: '번역 미리보기: 새로 온 근로자에게 알려주는 안전한 기록 습관입니다.',
    isSafetyReport: true,
    likeCount: 124,
    commentCount: 15,
    viewCount: 844,
    saved: true,
    comments: ['이 글 저장합니다. 새 친구들에게 보여줄게요.', '근무시간도 메모해두면 좋아요.', '맞아요. 카톡 대화도 중요한 내용은 캡처해두세요.'],
    reported: 0,
    images: [],
  },
  {
    id: 10,
    groupId: 'ansan-vn',
    boardId: 'free',
    title: '월요일 아침 서로 커피 사주는 동료들',
    author: 'Anil',
    ...sampleUserFields(13),
    category: '회사생활',
    body: '월요일 아침은 다들 조용한데, 한 명이 캔커피 사오면 분위기가 조금 좋아져요. 말이 많이 통하지 않아도 작은 친절은 바로 느껴집니다.',
    languageCode: 'ko',
    originalLanguage: '한국어',
    translatedText: '번역 미리보기: 월요일 아침 동료의 작은 친절에 대한 따뜻한 글입니다.',
    likeCount: 77,
    commentCount: 8,
    viewCount: 457,
    comments: ['작은 친절이 오래 기억나요.', '저희 회사도 금요일마다 커피 한 명씩 삽니다.', '말보다 행동으로 친해질 때가 있어요.'],
    reported: 0,
    images: [],
  },
  {
    id: 11,
    groupId: 'jeonbuk-e9-e8',
    boardId: 'workplace',
    title: '전북 농장 숙소와 출퇴근 정보 공유해요',
    author: 'Minh',
    ...sampleUserFields(14),
    category: '농업근로',
    body: '전북 농장으로 이동하기 전에 숙소, 출퇴근 차량, 장보기 위치를 미리 알고 싶습니다. 이미 일하고 있는 분들은 준비하면 좋은 물건이나 조심할 점을 알려주세요.',
    languageCode: 'ko',
    originalLanguage: '한국어',
    translatedText: '번역 미리보기: 전북 농업현장 근무 전 숙소와 생활 준비 정보를 묻는 글입니다.',
    likeCount: 46,
    commentCount: 6,
    viewCount: 318,
    comments: ['장화와 얇은 긴팔은 꼭 챙기세요.', '숙소 주소랑 마트 위치를 첫날에 저장해두면 편해요.', '통역 가능한 관리자 연락처도 확인하세요.'],
    reported: 0,
    images: [],
  },
  {
    id: 12,
    groupId: 'jeonbuk-e9-e8',
    boardId: 'qna',
    title: 'E-8 계절근로 계약 기간 확인 질문',
    author: 'Sokha',
    ...sampleUserFields(15),
    category: 'Q&A',
    body: 'E-8 계절근로로 전북에 가는 친구가 계약 기간과 휴무일을 확인하고 있습니다. 계약서에서 꼭 봐야 하는 항목이 있으면 알려주세요.',
    languageCode: 'ko',
    originalLanguage: '한국어',
    translatedText: '번역 미리보기: E-8 계절근로 계약서 확인 항목을 묻는 질문입니다.',
    likeCount: 39,
    commentCount: 5,
    viewCount: 276,
    comments: ['근무시간, 휴게시간, 숙식비 공제 항목을 꼭 보세요.', '계약서 사진을 저장해두면 나중에 확인하기 좋아요.', '모르는 항목은 서명 전에 통역 도움을 받으세요.'],
    reported: 0,
    images: [],
  },
  {
    id: 13,
    groupId: 'jeonbuk-e9-e8',
    boardId: 'free',
    title: '전북 농업현장 다국어 안내 모아봐요',
    author: 'Nara',
    ...sampleUserFields(16),
    category: '지역정보',
    body: '병원, 은행, 외국인 지원센터, 버스터미널처럼 처음 오면 필요한 장소를 언어별로 정리하면 좋겠습니다. 아는 정보가 있으면 댓글로 남겨주세요.',
    languageCode: 'ko',
    originalLanguage: '한국어',
    translatedText: '번역 미리보기: 전북 지역 생활 필수 장소와 다국어 안내를 함께 모으자는 글입니다.',
    likeCount: 52,
    commentCount: 8,
    viewCount: 351,
    comments: ['군청 외국인 담당 부서 번호를 저장해두면 좋아요.', '병원 갈 때 증상 번역 문장을 미리 준비하세요.', '버스 시간표 사진도 공유하면 좋겠어요.'],
    reported: 0,
    images: [],
  },
]

export const initialPosts: Post[] = [
  ...relatableCommunityPosts,
  ...Array.from({ length: 50 }, (_, index) => ({
  id: index + 14,
  groupId: communityGroups[index % communityGroups.length].id,
  boardId: ['free', 'qna', 'workplace', 'help', 'safety'][index % 5],
  title: ['근로계약서 확인 항목', '주말 한국어 수업 질문', '기숙사 생활 팁', '병원 통역 가능한 곳', '급여명세서 보는 법'][index % 5] + ` ${index + 11}`,
  author: authors[index % authors.length],
  ...sampleUserFields(index + 3),
  category: ['노동정보', '생활질문', '일자리후기', 'Q&A'][index % 4],
  body: '개인정보를 제외하고 경험을 공유합니다. 신고, 숨김, 삭제 검수가 가능한 커뮤니티 게시글 샘플입니다.',
  languageCode: ['ko', 'vi', 'en', 'zh', 'uz'][index % 5],
  originalLanguage: ['한국어', 'Tiếng Việt', 'English', '中文', "O'zbekcha"][index % 5],
  translatedText: '번역 미리보기: 개인정보를 제외하고 안전하게 경험을 공유합니다.',
  isNotice: index % 17 === 0,
  isAnonymous: index % 11 === 0,
  isSafetyReport: index % 9 === 0 || index % 5 === 4,
  likeCount: 4 + ((index * 3) % 48),
  commentCount: 1 + (index % 8),
  viewCount: 24 + index * 9,
  saved: index % 10 === 0,
  comments: [`댓글 샘플 ${index + 11}: 기관 안내와 실제 경험을 함께 확인해보세요.`],
  reported: index % 9 === 0 ? 2 : index % 7 === 0 ? 1 : 0,
  images: index % 6 === 0 ? [`community-${index + 1}.jpg`] : [],
  hidden: index % 31 === 0,
})),
]

export const communityComments: CommunityComment[] = Array.from({ length: 50 }, (_, index) => ({
  id: index + 1,
  postId: (index % initialPosts.length) + 1,
  author: authors[(index + 3) % authors.length],
  authorId: Number(sampleUsers[(index + 3) % sampleUsers.length].id),
  body: `댓글 샘플 ${index + 51}: 정확한 기관 안내를 확인하세요.`,
  reported: index % 10 === 0 ? 1 : 0,
}))

export const initialReports: HelpReport[] = Array.from({ length: 10 }, (_, index) => ({
  id: `H-${1024 + index}`,
  type: helpTypes[index % helpTypes.length],
  status: ['received', 'reviewing', 'agencyGuided', 'userAnswered', 'closed'][index % 5] as HelpReport['status'],
  content: '긴급 신고 대체가 아니라 관련 기관 안내와 상담 기록 관리를 위한 샘플입니다.',
  attachment: index % 3 === 0 ? `help-${index + 1}.jpg` : undefined,
}))

export const initialAdminReports: AdminReport[] = Array.from({ length: 24 }, (_, index) => {
  const targetTypes: AdminReport['targetType'][] = ['daily', 'post', 'comment', 'job', 'place']
  return {
    id: `RP-${201 + index}`,
    targetType: targetTypes[index % targetTypes.length],
    targetId: String((index % 20) + 1),
    reason: ['개인정보 노출 가능성', '얼굴 사진 검수 필요', '사업장 내부 사진 의심', '불법 알선 표현 의심', '혐오 표현 신고'][index % 5],
    status: ['received', 'reviewing', 'actioned', 'rejected', 'closed'][index % 5] as AdminReport['status'],
    reporter: index % 4 === 0 ? 'system' : authors[index % authors.length],
    createdAt: index < 8 ? `오늘 ${10 + index}:05` : `${index % 5 + 1}일 전`,
  }
})

export const initialAdminLogs: AdminLog[] = Array.from({ length: 12 }, (_, index) => ({
  id: index + 1,
  admin: '운영자',
  action: ['장소 검수', '피드 숨김', '신고 상태 변경', '회원 경고'][index % 4],
  target: ['장소 제보', '일상 피드', '신고 RP', '작성자'][index % 4],
  detail: 'admin_logs에 저장되는 관리자 처리 이력 샘플',
  createdAt: index < 3 ? `오늘 ${14 + index}:00` : `${index}일 전`,
}))

export const notices: string[] = [
  '불법 수수료 요구 주의',
  '산재 발생 시 가까운 지원센터 상담 가능',
  '장소와 일자리 제보는 관리자 승인 후 노출됩니다',
  '개인정보와 얼굴 사진이 포함된 게시물은 숨김 처리될 수 있습니다',
  '도움 요청은 기관 안내와 기록 관리 중심으로 운영됩니다',
]

export const noticeRecords: Notice[] = notices.map((title, index) => ({
  id: index + 1,
  title,
  body: `${title} 관련 다국어 공지 샘플입니다.`,
  published: index !== 4,
}))

export const banners: Banner[] = Array.from({ length: 5 }, (_, index) => ({
  id: index + 1,
  title: ['오늘의 한국생활', '급여명세서 확인 주간', '내 주변 상담센터', '안전한 숙소 생활', '커뮤니티 질문 모음'][index],
  body: ['생활 팁과 장소 정보를 함께 확인하세요.', '시급, 근무시간, 공제 항목을 기록하세요.', '언어 지원 장소를 지도로 찾을 수 있습니다.', '정확한 주소 대신 시/군/구 단위로 공유하세요.', '질문은 커뮤니티 Q&A로 이어집니다.'][index],
  image: `https://picsum.photos/seed/workhere-banner-${index + 1}/900/360`,
  published: index !== 3,
}))

export const savedItems: SavedItem[] = Array.from({ length: 36 }, (_, index) => ({
  id: index + 1,
  userId: (index % users.length) + 1,
  targetType: ['daily', 'post', 'job', 'place'][index % 4] as SavedItem['targetType'],
  targetId: (index % 30) + 1,
}))
